version: 1.0.{build}
build: off
test_script:
- ps: $wc = New-Object 'System.Net.WebClient'

- ps: $wc.UploadFile("http://appveyor.local/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\nunitlite-different-time-format-result.xml))
- ps: $wc.UploadFile("http://appveyor.local/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\xunit-result.xml))
- ps: $wc.UploadFile("http://appveyor.local/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\xunit20-result.xml))
- ps: $wc.UploadFile("http://appveyor.local/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\nunit-result.xml))
- ps: $wc.UploadFile("http://appveyor.local/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\nunit3-result.xml))
- ps: $wc.UploadFile("http://appveyor.local/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\mstest-result.xml))

